type Query {
  messages: [Message]
}

type Mutation {
  addMessage(user: String!, message: String!): Message
}

type Subscription {
  messageAdded: Message
}

type Message {
  id: ID!
  user: String
  message: String
}
